#!/bin/bash
./reco_sys.py data/mini_data.csv 1 700
./reco_sys.py data/mini_data.csv 1 650
./reco_sys.py data/mini_data.csv 1 600
./reco_sys.py data/mini_data.csv 1 550
./reco_sys.py data/mini_data.csv 1 500
./reco_sys.py data/mini_data.csv 1 450
./reco_sys.py data/mini_data.csv 1 400
./reco_sys.py data/mini_data.csv 1 350
./reco_sys.py data/mini_data.csv 1 300
./reco_sys.py data/mini_data.csv 1 250
./reco_sys.py data/mini_data.csv 1 200
./reco_sys.py data/mini_data.csv 1 150
./reco_sys.py data/mini_data.csv 1 100
./reco_sys.py data/mini_data.csv 1 50
./reco_sys.py data/mini_data.csv 1 1
./reco_sys.py data/mini_data.csv 2 50
./reco_sys.py data/mini_data.csv 3 50
./reco_sys.py data/mini_data.csv 4 50
./reco_sys.py data/mini_data.csv 5 50
./reco_sys.py data/mini_data.csv 3 49
./reco_sys.py data/mini_data.csv 3 48
./reco_sys.py data/mini_data.csv 3 47
./reco_sys.py data/mini_data.csv 3 51
./reco_sys.py data/mini_data.csv 3 52
./reco_sys.py data/mini_data.csv 3 53
